services:
  - type: web
    name: apk-scanner-backend
    env: python
    plan: free
    buildCommand: cd apk_scanner_pro && pip install -r requirements.txt
    startCommand: cd apk_scanner_pro && python api_server.py
    autoDeploy: true
