services:
  - type: web
    name: apk-scanner-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn apk_scanner_pro.api_server:app --bind 0.0.0.0:$PORT --workers 2


